export const actionType = {
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  GET_ALL_EXPENSES: 'GET_ALL_EXPENSES',
  GET_TODAY_EXPENSE: 'GET_TODAY_EXPENSE',
  GET_DAILY_EXPENSE: 'GET_DAILY_EXPENSE',
  GET_EXPENSE_BY_TYPE: 'GET_EXPENSE_BY_TYPE',
  GET_LATES_EXPENSE: 'GET_LATES_EXPENSE',
};
